#!/usr/bin/env python3
"""Normalize the ``speakers`` field in quotes.json and regenerate the
canonical character list.

The script is idempotent. Running it repeatedly on an already-normalized file
produces no changes.

    python scripts/normalize_speakers.py           # rewrite quotes.json + list
    python scripts/normalize_speakers.py --check   # verify only, no writes

``--check`` exits non-zero when a quote names a character that is not
canonical, or when ``list-of-characters.txt`` does not match the names in use.
It is what CI runs to enforce the naming rule described in CONTRIBUTING.md.

A name that does not resolve to a canonical character is a hard error in both
modes: the script writes nothing and exits non-zero until either the quote is
corrected or the character is added to ``scripts/speaker_names.py``. It never
normalizes around an unknown name, because doing so would delete a name a
curator wrote and leave a record that looks correct afterwards.

An unrecognized ``Name:`` prefix inside the quote text is only a warning. That
detection is a heuristic and the quote text is never modified, so nothing is
lost -- it just means a speaker in the text went unrecorded.
"""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from speaker_names import (  # noqa: E402
    format_speakers,
    parse_speakers,
    resolve,
    split_speakers,
    unknown_prefixes,
)

DATA_DIR = Path(__file__).parent.parent / "app" / "data"
QUOTES_PATH = DATA_DIR / "quotes.json"
CHARACTERS_PATH = DATA_DIR / "list-of-characters.txt"

# Stored key order, so the rewritten file stays readable in diffs.
KEY_ORDER = ["id", "quote", "speakers", "imageUrl"]


def normalize_quote(quote: dict) -> tuple[dict, list[str]]:
    """Return a normalized copy of ``quote`` plus any unresolvable names.

    Names already present in ``speakers`` win, then the legacy
    ``primarySpeaker``, then any speakers parsed out of the quote text.

    An unresolvable name is reported, never discarded. The caller must refuse
    to write anything while one exists -- dropping it would silently delete a
    curator's work, and the record would look correct afterwards.
    """
    problems: list[str] = []
    names: list[str] = []

    def add(raw: str) -> None:
        canonical = resolve(raw)
        if canonical is None:
            problems.append(raw)
            # Keep the unresolved name in place so that a bug in the caller
            # cannot turn this into data loss.
            if raw not in names:
                names.append(raw)
        elif canonical not in names:
            names.append(canonical)

    for raw in split_speakers(quote.get("speakers", "")):
        add(raw)

    legacy = (quote.get("primarySpeaker") or "").strip()
    if legacy:
        add(legacy)

    for parsed in parse_speakers(quote.get("quote", "")):
        if parsed not in names:
            names.append(parsed)

    normalized = {k: v for k, v in quote.items() if k != "primarySpeaker"}
    normalized["speakers"] = format_speakers(names)
    ordered = {k: normalized[k] for k in KEY_ORDER if k in normalized}
    ordered.update({k: v for k, v in normalized.items() if k not in ordered})
    return ordered, problems


def display_path(path: Path) -> str:
    """Path relative to the working directory, or absolute if it is elsewhere."""
    try:
        return str(path.relative_to(Path.cwd()))
    except ValueError:
        return str(path)


def characters_in_use(quotes: list[dict]) -> list[str]:
    names = {n for q in quotes for n in split_speakers(q.get("speakers", ""))}
    return sorted(names, key=str.lower)


def render_character_list(names: list[str]) -> str:
    header = (
        "# Canonical Arrested Development character names.\n"
        "#\n"
        "# Generated by scripts/normalize_speakers.py -- do not edit by hand.\n"
        "# Every name in the `speakers` field of app/data/quotes.json must appear\n"
        "# here verbatim. See CONTRIBUTING.md for how to add a new character.\n"
        "#\n"
        "# `Lucille` is Lucille Bluth. Lucille Austero is always written out.\n"
        "\n"
    )
    return header + "".join(f"{name}\n" for name in names)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify without writing; exit non-zero if anything is off",
    )
    args = parser.parse_args()

    quotes = json.loads(QUOTES_PATH.read_text(encoding="utf-8"))

    normalized: list[dict] = []
    unknown_names: list[str] = []
    warnings: list[str] = []
    for quote in quotes:
        result, bad = normalize_quote(quote)
        normalized.append(result)
        for name in bad:
            unknown_names.append(f"{quote['id']}: unknown character name {name!r}")
        for prefix in unknown_prefixes(quote.get("quote", "")):
            # Not fatal: the quote text is never modified, so nothing is lost.
            # This only means a speaker in the text went unrecorded, and the
            # detection is a heuristic that can misfire on ordinary punctuation.
            warnings.append(
                f"{quote['id']}: unrecognized speaker prefix {prefix!r} in quote text"
            )

    # An unknown name stops everything, in both modes. Normalizing around it
    # would erase a name a curator deliberately wrote.
    if unknown_names:
        for problem in unknown_names:
            print(f"ERROR: {problem}", file=sys.stderr)
        print(
            f"\n{len(unknown_names)} unknown character name(s); nothing was written.\n"
            "\nFix each one before re-running:\n"
            "  - misspelling or variant of an existing character?\n"
            "    Use the canonical spelling from app/data/list-of-characters.txt,\n"
            "    or add the variant as an alias in scripts/speaker_names.py.\n"
            "  - a character who is not on the list yet?\n"
            "    Add them to the CHARACTERS dict in scripts/speaker_names.py.\n"
            "\nSee CONTRIBUTING.md#character-names.",
            file=sys.stderr,
        )
        return 1

    names = characters_in_use(normalized)
    expected_list = render_character_list(names)
    quotes_json = json.dumps(normalized, indent=2, ensure_ascii=False) + "\n"

    for warning in warnings:
        print(f"WARNING: {warning}", file=sys.stderr)

    if args.check:
        problems: list[str] = []
        if not CHARACTERS_PATH.exists():
            problems.append(f"{CHARACTERS_PATH.name} is missing")
        elif CHARACTERS_PATH.read_text(encoding="utf-8") != expected_list:
            problems.append(
                f"{CHARACTERS_PATH.name} is stale; run scripts/normalize_speakers.py"
            )
        if QUOTES_PATH.read_text(encoding="utf-8") != quotes_json:
            problems.append(
                "quotes.json is not normalized; run scripts/normalize_speakers.py"
            )
        for problem in problems:
            print(f"ERROR: {problem}", file=sys.stderr)
        if problems:
            print(f"\n{len(problems)} problem(s) found.", file=sys.stderr)
            return 1
        print(f"OK: {len(normalized)} quotes, {len(names)} canonical characters.")
        return 0

    QUOTES_PATH.write_text(quotes_json, encoding="utf-8")
    CHARACTERS_PATH.write_text(expected_list, encoding="utf-8")

    attributed = sum(1 for q in normalized if q["speakers"])
    print(f"Wrote {display_path(QUOTES_PATH)}: {len(normalized)} quotes, "
          f"{attributed} attributed, {len(normalized) - attributed} unattributed.")
    print(f"Wrote {display_path(CHARACTERS_PATH)}: {len(names)} characters.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
